### ISSUE TITLE
android12中出现问题

### ISSUE THREAD

**Issue by yuguzc** [getActivity/AndroidProject#105]
## 问题描述

* 框架版本【必填】：最新版，2022/11/29日拉下来的

* 问题描述【必填】：android技术中心在android12版本的手机打开时会报错。

* 复现步骤【必填】：打开app时，logcat中会显示

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：xiaomi，红米K30U

* 出现问题的安卓版本【必填】：android12

## 请回答

* 是部分机型还是所有机型都会出现【必答】：小米K30U，android12版本中会出现

* AndroidProject 最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：否

* 使用原生的权限 API 是否会出现该问题【必答】：否

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
* W/System.err: org.json.JSONException: No value for cezanne
*  W/System.err:     at com.hjq.base.BaseActivity.initLayout(BaseActivity.java:74)
* at com.hjq.demo.app.AppActivity.initLayout(AppActivity.java:96)
* at com.hjq.base.BaseActivity.initActivity(BaseActivity.java:49)
* at com.hjq.demo.ui.activity.SplashActivity.initActivity(SplashActivity.java:106)
* at com.hjq.base.BaseActivity.onCreate(BaseActivity.java:45)
* 以及
* java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl

* 提供截图或视频（根据需要提供，此项不强制）
* 
![image](https://user-images.githubusercontent.com/91948247/204446500-e15267ae-b6b9-44db-9d87-e9543630cda9.png)

![image](https://user-images.githubusercontent.com/91948247/204446563-f6bc785c-670d-4bdd-aaa6-fa71be309178.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/28616817/204549487-cb2044e3-2c94-4644-9891-a4c1ba765849.png">

**Comment by getActivity** [comment]
* 小伙子，从你的描述来看，AndroidProject 代码本身没有问题，大概率是你没看清楚代码就改它导致的问题，这种属于个人的使用问题，需要你自行排查和处理。

* 至于我为什么不排查和处理此类问题，因为开源本身不挣钱，我不会给某个人充当免费的劳动力，并为它个人的错误买单。

* 除非你出现的这个问题是框架的代码写得有问题，这样会涉及所有人，我才会处理，如果只是你个人出现的使用问题，需要你自己处理，我不会参与这个过程。

**Comment by yuguzc** [comment]
大佬你好。项目是我拉下来的，没有经过任何改动，

**Comment by yuguzc** [comment]
大佬你好。很感谢你的开源项目在百忙之中回复我，首先项目是我拉下来的，没有经过任何改动，在Android12机器上发生的问题，是否通过AndroidProject工程复现问题那里，可能是当时没有看清楚，应该是，是

**Comment by yuguzc** [comment]
大佬你好。很感谢你的开源项目给到我的帮助，而且在百忙之中回复我，首先项目是我拉下来的，没有经过任何改动，在Android12机器上发生的问题，是否通过AndroidProject工程复现问题那里，可能是当时没有看清楚，应该是，是

**Comment by getActivity** [comment]
小伙子，我试过了，用两台不同的红米 K30 测试，均没有发现任何问题

![](https://user-images.githubusercontent.com/28616817/204802619-fa6d3565-cd90-48b3-b54f-ffffe257be8b.png)

![](https://user-images.githubusercontent.com/28616817/204802936-6b737dae-3b5a-40aa-8983-e18e6ab18ad7.png)

**Comment by getActivity** [comment]
你试一下其他机型有没有这个问题？

**Comment by yuguzc** [comment]
你好，我认为是我这部机器的问题，因为错误中多次出现mediatek的错误，其他的android12机器未发现此问题。最后很感谢抽出时间来评定此问题。谢谢

**Comment by getActivity** [comment]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/28616817/205330833-3ab90c7d-a71e-4211-846c-07405fde57a9.png">

小伙子，你知道我为什么要求每一个人严格填写 issue 么？issue 模板填写的是《是部分机型还是所有机型都会出现》，你的回答是《小米K30U，android12版本中会出现》，这种回答本身就是牛唇不对马嘴，你如果有严格按照 issue 模板填写就不会提这个 issue 了，但是这次就算了，下次提 issue 需要额外注意，下次遇到这种回答我会直接打回不受理。

**Comment by YinRuizhe** [comment]
我也遇到了这个问题，一模一样的报错我的是红米10X，安卓12。具体是安卓studio里的一个空包都会报这个错误，可能会导致第二次安装的软件失效崩溃。

**Comment by YinRuizhe** [comment]
我也遇到了这个问题，一模一样的报错我的是红米10X，安卓12。所有的app在调试的时候都会报这个错误，可能会导致第二次安装的软件失效崩溃。有的可能正常运行。
[static] ClassNotFoundException
                                                                                                    java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at java.lang.Class.forName(Class.java:379)
                                                                                                    	at com.mediatek.view.MsyncFactory.<clinit>(MsyncFactory.java:14)
                                                                                                    	at com.mediatek.view.MsyncFactory.getInstance(MsyncFactory.java:29)
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:761)
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:857)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:393)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5012)
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8274)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
                                                                                                    Caused by: java.lang.ClassNotFoundException: com.mediatek.view.impl.MsyncFactoryImpl
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.BootClassLoader.findClass(ClassLoader.java:1358)
                                                                                                    	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1418)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at java.lang.Class.classForName(Native Method) 
                                                                                                    	at java.lang.Class.forName(Class.java:454) 
                                                                                                    	at java.lang.Class.forName(Class.java:379) 
                                                                                                    	at com.mediatek.view.MsyncFactory.<clinit>(MsyncFactory.java:14) 
                                                                                                    	at com.mediatek.view.MsyncFactory.getInstance(MsyncFactory.java:29) 
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:761) 
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:857) 
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:393) 
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134) 
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5012) 
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54) 
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8274) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
