### ISSUE TITLE
又出现了 不清楚是什么问题。

### ISSUE THREAD

**Issue by liwenlong15139561730** [getActivity/AndroidProject#132]
## 问题描述

* 框架版本【必填】：31

* 问题描述【必填】：一直崩溃 闪退

* 复现步骤【必填】：运行起来打开就

* 是否必现【必填】：否

* 出现问题的手机信息【必填】：小米

* 出现问题的安卓版本【必填】：API31

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分/全部（例如：某为，某 Android 版本会出现）

* AndroidProject 最新的版本是否存在这个问题【必答】：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的【必答】：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题【必答】：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 AndroidProject 工程来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的权限 API 是否会出现该问题【必答】：是/否（排查一下是不是 AndroidProject 的代码存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by liwenlong15139561730** [comment]
Process: com.neoinfo.epms.debug:crash, PID: 14086
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.neoinfo.epms.debug/com.neoinfo.epms.ui.activity.CrashActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3773)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3940)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2318)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8299)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                                                    	at com.hjq.base.action.ClickAction.setOnClickListener(ClickAction.java:34)
                                                                                                    	at com.hjq.base.action.ClickAction.setOnClickListener(ClickAction.java:29)
                                                                                                    	at com.neoinfo.epms.ui.activity.CrashActivity.initView(CrashActivity.java:103)
                                                                                                    	at com.hjq.base.BaseActivity.initActivity(BaseActivity.java:50)
                                                                                                    	at com.hjq.base.BaseActivity.onCreate(BaseActivity.java:45)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8187)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8153)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3746)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3940) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2318) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8299) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by liwenlong15139561730** [comment]
使用的startActivity()方法。也有设置setOnClickListener(mCommitView, mServerView); 但一直报空指针异常。不清楚是哪里在报错，错误提示的再基础框架里面setOnClickListener(android.view.View$OnClickListener)' on a null object reference

**Comment by liwenlong15139561730** [comment]
我找到 什么问题了，build的文件的问题，可能是因为clean了 导致一些文件丢失造成的吧

**Comment by liwenlong15139561730** [comment]
找到问题了，clean导致build的文件丢失吧
